# Generated by Django 5.0.6 on 2024-05-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='constraints',
            new_name='test_cases',
        ),
    ]
