# Generated by Django 5.0.6 on 2024-06-14 04:26

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Theme = apps.get_model('problems', 'Theme')
    for theme in Theme.objects.all():
        theme.slug = slugify(theme.name)
        theme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_userproblem_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
