# Generated by Django 5.0.6 on 2024-06-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_mig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
