# Generated by Django 5.0.6 on 2024-06-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
