# Generated by Django 5.0.6 on 2024-06-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_problem_slug_alter_theme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
